version: '3'
services:
  backend:
    build: backend/
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - PORT=5000
      - DB_URL=mysql+pymysql://root:password@db:3306/database
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

  frontend:
    build:
      context: frontend/
      args:
        - RVT_BACKEND=${RVT_BACKEND:-http://localhost:5000}
    ports:
      - 3000:3000
    depends_on:
      - backend

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
  